[package]
name = "all_places_patterns_can_be_used"
version = "0.1.0"
authors = ["Helgard Richard Ferreira <hrfer3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
