[package]
name = "utf8_encoded_strings"
version = "0.1.0"
authors = ["Helgard Richard Ferreira <hferreira@mezzanineware.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
